### ISSUE TITLE
MKS converter name swapped to "USI_Converter"

### ISSUE THREAD

**Issue by LouisCyfer** [ChrisAdderley/NearFutureElectrical#122]
Please make sure you have the right converter replaced in [NFElectricalUSIReactors.cfg](https://github.com/ChrisAdderley/NearFutureElectrical/blob/master/GameData/NearFutureElectrical/Patches/NFElectricalUSIReactors.cfg) the latest version of MKS (state of writing version 1.3.0.0) has different converter modules named "USI_Converter" instead of "ModuleResourceConverter". However, I'm unsure if this will change but writing a small script helped getting off the double-reactor controls while it looks like it removes the correct converter modules.

```
@PART[Tundra_PDU,Duna_PDU,USI_Nuke_*,FTT_Service_375_01,FTT_Reactor_500_01]:HAS[@MODULE[USI_Converter]]:NEEDS[MKS&NearFutureElectrical]:FINAL
{
	!MODULE[USI_Converter]{}
}
```
You might want to add :NEEDS[MKS] at each @PART-line aswell to make sure it only applies to the parts when MKS is installed/found.

Thanks for your work!

**Comment by Wyzard256** [comment]
This looks like the right thing to do, but instead of adding the patch above as a new file, it'd make more sense to incorporate the change directly into NFElectricalUSIReactors.cfg.  Remove the `!MODULE[ModuleResourceConverter]{}` or `!MODULE[ModuleResourceConverter_USI]{}` for the affected parts, and add the `!MODULE[USI_Converter]{}` line instead.

**Comment by LouisCyfer** [comment]
The temp config I wrote was to verify functionality in first place, no worries. Love to see the NF-line evolving!

**Comment by ChrisAdderley** [comment]
Fix is ready in dev, will be in next release

**Comment by ChrisAdderley** [comment]
Released.
